name: Upload Python Package

on:
  release:
    types: [published]
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine build

      - name: "Build package"
        run: python -m build

      - name: "Publish package"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          verbose: true
